# Parallel job definitions
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/multiple-phases

# jobs:
# - job: InitialJob
#   strategy:
#     parallel: 2
#   steps:
#   - script: echo hello from initial job
# - job: SubsequentA
#   dependsOn: InitialJob
#   steps:
#   - script: echo hello from subsequent A
# - job: SubsequentB
#   dependsOn: InitialJob
#   steps:
#   - script: echo hello from subsequent B

jobs:
- job: InitialJob
  strategy:
    parallel: 2
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - script: echo hello from initial job
